### ISSUE TITLE
[FEATURE] Add the connection string to the github secrets

### ISSUE THREAD

**Issue by tocee123** [tocee123/Stocks#66]
**Is your feature request related to a problem? Please describe.**
Find a way to upload appconfig.json to secrets

[link](https://stackoverflow.com/questions/60521929/change-variables-in-appsettings-when-deploying-with-github-actions)

```yaml
#substitute production appsettings entries to appsettings json file
- name: App Settings Variable Substitution
  uses: microsoft/variable-substitution@v1
  with:
    files: '${{env.DOTNET_ROOT}}/myapp/appsettings.json'
  env:
    ConnectionStrings.Default: ${{ secrets.SOME_CONNECTION_STRING }}
    App.ServerRootAddress: ${{ env.SERVER_ROOT_ADDRESS }}
```
